# A remote index file, already set up for Meilisearch.
- name: docs
  type: remote
  # Acts as a rank override for a remote index.
  rank: 1
  url:  "https://docs.platform.sh/"
  file: "index.json"
  destination: "output/docs.json"

# Community Site
- name: discourse
  type: discourse
  rank: 4
  url: "https://community.platform.sh/"
  destination: "output/community.json"
  # Categories to ignore
  # ignore:
    # - "Activity Scripts"

# API Documentation (OpenAPI 3.0 Spec)
- name: openapi
  type: openapi
  url: "https://api.platform.sh/docs/"
  file: "openapispec-platformsh.json"
  destination: "output/apidocs.json"
  rank: 5
  # Path tags that if present, causes that path to be ignored.
  ignore:
    - "NO_INCLUDE"
